name: CI

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
    - name: Run a one-line script
      shell: pwsh
      run: ./tools/EhDbReleaseBuilder/Download-Tool.ps1
    - name: Run a multi-line script
      run: dotnet ./tools/EhDbReleaseBuilder/EhDbReleaseBuilder.dll . ./publish
