name: CI

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.402'
    - name: Install tools
      shell: pwsh
      run: ./tools/EhDbReleaseBuilder/Download-Tool.ps1
      env:
        GitHub:Token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: dotnet ./tools/EhDbReleaseBuilder/EhDbReleaseBuilder.dll . ./publish
    - uses: ncipollo/release-action@v1
      with:
        artifacts: ./publish/*.js,./publish/*.json,./publish/*.gz
        bodyFile: ./publish/message.md
        token: ${{ secrets.GITHUB_TOKEN }}
