name: build

on: 
  push:
    branches:
    - master
    paths:
    - database/*

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: init git config
      run: |
        git config --global user.email '66814738+ehtagtranslation[bot]@users.noreply.github.com>'
        git config --global user.name  'ehtagtranslation[bot]'
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.402
    - name: Install tools
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./tools/EhDbReleaseBuilder/Download-Tool.ps1
    - name: Build
      run: dotnet ./tools/EhDbReleaseBuilder/EhDbReleaseBuilder.dll --source . --target ./publish
    - name: Set messages
      run: |
        echo "::set-env name=RELEASE_NAME::$(
        head -n1 <<EOF
        ${{github.event.head_commit.message}}
        EOF
        )"
    - name: Upload release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ./publish/*
        body: |
          ${{github.event.before}}...${{github.event.after}}
          
          ${{github.event.head_commit.message}}
        token: ${{ secrets.GITHUB_TOKEN }}
        commit: ${{ github.sha }}
        tag: ${{ format('v-{0}', github.sha) }}
        name: ${{ env.RELEASE_NAME }}
    - name: Commit release branch
      run: >
        cd ./publish &&
        git init &&
        git add . &&
        git commit -am 'Release for ${{ github.sha }}'
    - name: Push release branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: release
        force: true
        directory: ./publish
    - name: Clean releases
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ./tools/RemoveOldReleases/
        yarn install --no-lockfile
        yarn start
 
