name: build

on: 
  push:
    branches:
    - master
    paths:
    - database/*

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.402
    - name: Install tools
      shell: pwsh
      run: ./tools/EhDbReleaseBuilder/Download-Tool.ps1
      env:
        GitHub:Token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: dotnet ./tools/EhDbReleaseBuilder/EhDbReleaseBuilder.dll . ./publish
    - name: Dump
      run: |
        cat <<EOF
        ${{toJSON(github)}}
        EOF
    - uses: ncipollo/release-action@v1
      with:
        artifacts: ./publish/*
        body: ${{ format('{0}...{1}\n\n{2}', github.event.before, github.event.after, github.event.head_commit.message) }}
        token: ${{ secrets.GITHUB_TOKEN }}
        commit: ${{ github.sha }}
        tag: ${{ format('v-{0}', github.sha) }}
        name: ${{ github.event.head_commit.message }}
